# Generated by Django 4.2.2 on 2023-07-05 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Course Name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Location Name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Default First Name', max_length=100)),
                ('last_name', models.CharField(default='Default Last Name', max_length=100)),
                ('location', models.CharField(default='Default Location', max_length=100)),
                ('phone_number', models.CharField(default='000-000-0000', max_length=15)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('space', models.CharField(default='Default Space', max_length=100)),
                ('gender', models.CharField(default='Other', max_length=10)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('password', models.CharField(default='password', max_length=100)),
                ('ranking', models.IntegerField(null=True)),
                ('courses', models.ManyToManyField(to='new_ranking.course')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Default First Name', max_length=100)),
                ('last_name', models.CharField(default='Default Last Name', max_length=100)),
                ('location', models.CharField(default='Default Location', max_length=100)),
                ('phone_number', models.CharField(default='000-000-0000', max_length=15)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('space', models.CharField(default='Default Space', max_length=100)),
                ('gender', models.CharField(default='Other', max_length=10)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_data', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='new_ranking.location')),
            ],
        ),
        migrations.CreateModel(
            name='PastRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_rankings', to='new_ranking.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='package',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_ranking.package'),
        ),
        migrations.AddField(
            model_name='member',
            name='trainer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_ranking.trainer'),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_data', models.CharField(default='Default Level Data', max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='new_ranking.course')),
            ],
        ),
    ]
